version: "3.7"
services:
  rclone:
    image: rclone:dev
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_credentials
    command: '"rclone sync --skip-links --max-age 1y /net/example.com/export/data/ default:data/"'
    volumes:
      - data:/net/example.com/export/data
    configs:
      - source: rclone
        target: /root/.config/rclone/rclone.conf
    secrets:
      - aws_credentials
    deploy:
      restart_policy:
        condition: any
        delay: 12h
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G
      placement:
        constraints:
          - "node.hostname == example.com"
volumes:
  data:
    driver_opts:
      type: nfs
      device: :/export/data
      o: addr=example.com
configs:
  rclone:
    file: rclone.conf
secrets:
  aws_credentials:
    file: .aws/credentials

